### ISSUE TITLE
Templates without TextPart crash the getTemplate call

### ISSUE THREAD

**Issue by GravlLift** [MattRuddick/aws-ses-template-manager#1]
I was working with a template that didn't have a TextPart (created outside of this application via cli). Trying to edit it resulted in a 500 error from the local server. I was able to patch it locally by simply adding an `if(TextPart)` to this line:

https://github.com/MattRuddick/aws-ses-template-manager/blob/bdc0b9ffebcede49dc2f367144da2f22310c3f25/app/Controllers/Http/SesTemplateController.js#L102

**Comment by MattRuddick** [comment]
Thanks for raising this! Now resolved 👍
